### ISSUE TITLE
Misleading Keywords

### ISSUE THREAD

**Issue by jdalrymple** [dy/get-pixel-data#13]
In the package.json it mentioned jpeg as a keyword, but when attempting to use this library with jpegs, I receive an error:

```
TypeError: Expected the `input` argument to be of type `Uint8Array` or `Buffer`, got `object`
    at fileType (/work/server/node_modules/file-type/index.js:21:9)
    at imageType (/work/server/node_modules/image-type/index.js:26:14)
    at decode (/work/server/node_modules/image-decode/index.js:20:12)
    at loadRaw (/work/server/node_modules/image-pixels/lib/raw.js:16:20)
    at /work/server/node_modules/image-pixels/index.js:148:11
```

Also, when I then try with a jpg I receive:

```
Error: Raw data requires options.width and options.height
    at loadRaw (/work/server/node_modules/image-pixels/lib/raw.js:19:32)
    at /work/server/node_modules/image-pixels/index.js:247:10
```

This is how im calling the function

```javascript
    let a = await pixels('test.jpg')
    let b = await pixels('test.jpeg')
```
Any ideas?

**Comment by jdalrymple** [comment]
Seems to be an issue with my images, though i can open them just fine. Ill close for now!

**Comment by jdalrymple** [comment]
Mentioned here https://github.com/sindresorhus/file-type/issues/191

**Comment by dy** [comment]
Can you please show the bad jpegs? Possibly some jpeg format config is broken, although it is handled by browser img tag.
